import { createRouter, RouterProvider } from "@tanstack/react-router";
import { routeTree } from "../src/routeTree.gen"; // Generated by TanStack Router CLI

const router = createRouter({ routeTree });

import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css"

// biome-ignore lint/style/noNonNullAssertion: <explanation>
ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);
