/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as ConfigureImport } from './routes/configure'
import { Route as LoginImport } from './routes/Login'
import { Route as FleetImport } from './routes/Fleet'
import { Route as ContactImport } from './routes/Contact'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as ConfigureIndexImport } from './routes/configure/index'
import { Route as FleetIndexImport } from './routes/Fleet/index'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'
import { Route as DashboardOverviewImport } from './routes/dashboard/overview'
import { Route as ConfigureMapImport } from './routes/configure/map'
import { Route as ConfigureAutomationImport } from './routes/configure/automation'
import { Route as FleetAddRobotImport } from './routes/Fleet/addRobot'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const ConfigureRoute = ConfigureImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRoute,
} as any)

const FleetRoute = FleetImport.update({
  id: '/Fleet',
  path: '/Fleet',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const ConfigureIndexRoute = ConfigureIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfigureRoute,
} as any)

const FleetIndexRoute = FleetIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FleetRoute,
} as any)

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardOverviewRoute = DashboardOverviewImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)

const ConfigureMapRoute = ConfigureMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => ConfigureRoute,
} as any)

const ConfigureAutomationRoute = ConfigureAutomationImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => ConfigureRoute,
} as any)

const FleetAddRobotRoute = FleetAddRobotImport.update({
  id: '/addRobot',
  path: '/addRobot',
  getParentRoute: () => FleetRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/Fleet': {
      id: '/Fleet'
      path: '/Fleet'
      fullPath: '/Fleet'
      preLoaderRoute: typeof FleetImport
      parentRoute: typeof rootRoute
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/Fleet/addRobot': {
      id: '/Fleet/addRobot'
      path: '/addRobot'
      fullPath: '/Fleet/addRobot'
      preLoaderRoute: typeof FleetAddRobotImport
      parentRoute: typeof FleetImport
    }
    '/configure/automation': {
      id: '/configure/automation'
      path: '/automation'
      fullPath: '/configure/automation'
      preLoaderRoute: typeof ConfigureAutomationImport
      parentRoute: typeof ConfigureImport
    }
    '/configure/map': {
      id: '/configure/map'
      path: '/map'
      fullPath: '/configure/map'
      preLoaderRoute: typeof ConfigureMapImport
      parentRoute: typeof ConfigureImport
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardImport
    }
    '/Fleet/': {
      id: '/Fleet/'
      path: '/'
      fullPath: '/Fleet/'
      preLoaderRoute: typeof FleetIndexImport
      parentRoute: typeof FleetImport
    }
    '/configure/': {
      id: '/configure/'
      path: '/'
      fullPath: '/configure/'
      preLoaderRoute: typeof ConfigureIndexImport
      parentRoute: typeof ConfigureImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface FleetRouteChildren {
  FleetAddRobotRoute: typeof FleetAddRobotRoute
  FleetIndexRoute: typeof FleetIndexRoute
}

const FleetRouteChildren: FleetRouteChildren = {
  FleetAddRobotRoute: FleetAddRobotRoute,
  FleetIndexRoute: FleetIndexRoute,
}

const FleetRouteWithChildren = FleetRoute._addFileChildren(FleetRouteChildren)

interface ConfigureRouteChildren {
  ConfigureAutomationRoute: typeof ConfigureAutomationRoute
  ConfigureMapRoute: typeof ConfigureMapRoute
  ConfigureIndexRoute: typeof ConfigureIndexRoute
}

const ConfigureRouteChildren: ConfigureRouteChildren = {
  ConfigureAutomationRoute: ConfigureAutomationRoute,
  ConfigureMapRoute: ConfigureMapRoute,
  ConfigureIndexRoute: ConfigureIndexRoute,
}

const ConfigureRouteWithChildren = ConfigureRoute._addFileChildren(
  ConfigureRouteChildren,
)

interface DashboardRouteChildren {
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Contact': typeof ContactRoute
  '/Fleet': typeof FleetRouteWithChildren
  '/Login': typeof LoginRoute
  '/configure': typeof ConfigureRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/Fleet/addRobot': typeof FleetAddRobotRoute
  '/configure/automation': typeof ConfigureAutomationRoute
  '/configure/map': typeof ConfigureMapRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/Fleet/': typeof FleetIndexRoute
  '/configure/': typeof ConfigureIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Contact': typeof ContactRoute
  '/Login': typeof LoginRoute
  '/Fleet/addRobot': typeof FleetAddRobotRoute
  '/configure/automation': typeof ConfigureAutomationRoute
  '/configure/map': typeof ConfigureMapRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/Fleet': typeof FleetIndexRoute
  '/configure': typeof ConfigureIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Contact': typeof ContactRoute
  '/Fleet': typeof FleetRouteWithChildren
  '/Login': typeof LoginRoute
  '/configure': typeof ConfigureRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/Fleet/addRobot': typeof FleetAddRobotRoute
  '/configure/automation': typeof ConfigureAutomationRoute
  '/configure/map': typeof ConfigureMapRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/Fleet/': typeof FleetIndexRoute
  '/configure/': typeof ConfigureIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Contact'
    | '/Fleet'
    | '/Login'
    | '/configure'
    | '/dashboard'
    | '/Fleet/addRobot'
    | '/configure/automation'
    | '/configure/map'
    | '/dashboard/overview'
    | '/dashboard/settings'
    | '/Fleet/'
    | '/configure/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Contact'
    | '/Login'
    | '/Fleet/addRobot'
    | '/configure/automation'
    | '/configure/map'
    | '/dashboard/overview'
    | '/dashboard/settings'
    | '/Fleet'
    | '/configure'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/Contact'
    | '/Fleet'
    | '/Login'
    | '/configure'
    | '/dashboard'
    | '/Fleet/addRobot'
    | '/configure/automation'
    | '/configure/map'
    | '/dashboard/overview'
    | '/dashboard/settings'
    | '/Fleet/'
    | '/configure/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FleetRoute: typeof FleetRouteWithChildren
  LoginRoute: typeof LoginRoute
  ConfigureRoute: typeof ConfigureRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FleetRoute: FleetRouteWithChildren,
  LoginRoute: LoginRoute,
  ConfigureRoute: ConfigureRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Contact",
        "/Fleet",
        "/Login",
        "/configure",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Contact": {
      "filePath": "Contact.tsx"
    },
    "/Fleet": {
      "filePath": "Fleet.tsx",
      "children": [
        "/Fleet/addRobot",
        "/Fleet/"
      ]
    },
    "/Login": {
      "filePath": "Login.tsx"
    },
    "/configure": {
      "filePath": "configure.tsx",
      "children": [
        "/configure/automation",
        "/configure/map",
        "/configure/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/overview",
        "/dashboard/settings",
        "/dashboard/"
      ]
    },
    "/Fleet/addRobot": {
      "filePath": "Fleet/addRobot.tsx",
      "parent": "/Fleet"
    },
    "/configure/automation": {
      "filePath": "configure/automation.tsx",
      "parent": "/configure"
    },
    "/configure/map": {
      "filePath": "configure/map.tsx",
      "parent": "/configure"
    },
    "/dashboard/overview": {
      "filePath": "dashboard/overview.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.tsx",
      "parent": "/dashboard"
    },
    "/Fleet/": {
      "filePath": "Fleet/index.tsx",
      "parent": "/Fleet"
    },
    "/configure/": {
      "filePath": "configure/index.tsx",
      "parent": "/configure"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
